### PR TITLE
Unguided project: Machine Learning - Translation

### PR DESCRIPTION
**Pull request by lamnhh**
- Added a page (/translator.html) for translating. Basically a cheap, low quality clone of google translate.

- Added feature to translate post.

### CODE REVIEW

**Comment by anhducle98** [comment]
Maybe there is a bug.
How to reproduce:
 - Post 2 different messages
 - Translate each of them
 - Both returns the same translation result (which should be different)

**Comment by lamnhh** [comment]
> Maybe there is a bug.
> How to reproduce:
> 
> * Post 2 different messages
> * Translate each of them
> * Both returns the same translation result (which should be different)

I just fixed it. Please review the PR again.

**Review by anhducle98 — APPROVED** [review]
Maybe it's better to exclude images from translation result.
Other than that everything is great!

**Comment by anhducle98** [comment]
If one tries to click on "Translate Post" quickly multiple times while it is still available (translation result not returned yet), multiple translation will show up.

**Comment by anhducle98** [comment]
Update: The above issue is fixed with commit https://github.com/anhducle98/team-47-codeu/commit/63c46be554c73bbc96ac2a7cd122f19f1aa7a207

**Pull request merged**
