### PR TITLE
Style the whole thing based on Twitter's design

### PR DESCRIPTION
**Pull request by lamnhh**
Style the whole thing based on Twitter's design. It will break severely on screen less than 992px wide (I think).

The following components are removed and merged into homepage:
- Community page (/community.html): display in the right sidebar.
- Links to /map and /bookchart: display in the right sidebar.
- Public feed: display in homepage.

### CODE REVIEW

**Comment by anhducle98** [comment]
Woaa looks great !!!
Could you make changes to the login page also?

**Comment by anhducle98** [comment]
Having two "Post" buttons on a page seems a bit redundant. I think we should keep just one on top. What do you think?

**Comment by lamnhh** [comment]
> Woaa looks great !!!
> Could you make changes to the login page also?

**Review by quanglm1998 — APPROVED** [review]
It's really cool!

**Review by anhducle98 — APPROVED** [review]
Nice!

**Comment by anhducle98** [comment]
The lower Post button is shown on all pages (About Us, Stats, ..) but doesn't work when clicked. I think we can safely remove it except on Homepage.

**Pull request merged**
